Misc:
    ddx: 0.0025
    ddy: 0.03
Colors:
    Days: "red3"
    Profile: "forestgreen"
    POIs: "royalblue4"
    Overview: "red"
    OverviewText: "red3"
Labels:
    xAxis: "Расстояние, км."
    yAxis: "Высота, м."
    Days: "Дни пути"
    OverviewStart: "Начало маршрута 24.08"
    OverviewEnd: "Окончание маршрута 07.09"
Dims:
    Width: 2040
    Height: 1400
Fontsize:
    Days: 6
    POIs: 7
    Axis_title: 20
    Axis_text: 18
Points:
    Size: 2.5
    Stroke: 1.75
fill:
    color1: "#88eb7c" 
    #"de3700" - red
    color2: "#008c00"
    #"#228b22" - forestgreen
    alpha: 0.15
