Misc:
    ddx: 0.0025
    ddy: 0.03
Colors:
    Days: "red3"
    Profile: "forestgreen"
    POIs: "royalblue4"
Labels:
    xAxis: "Расстояние, км."
    yAxis: "Высота, м."
    Days: "Дни пути"
Dims:
    Width: 2040
    Height: 1400
Fontsize:
    Days: 6
    POIs: 7
    Axis_title: 20
    Axis_text: 18
Points:
    Size: 3
    Stroke: 1
